# Site settings
title: silaizhe
SEOTitle: silaizhe的博客 | silaizhe's blog
header-img: img/index.png
email: wuchenlang244@gmail.com
description: ""
keyword: "电气 ,动画, 游戏"
url: "http://2633698.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/2633698/2633698.github.io" # you code repository
home_repo: "http://fujishiro.cn"

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: /img/head.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     
#zhihu_username:     
github_username:    2633698





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: silaizhe

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 1628acd4584b56ed9b40                            #生成的clientID
  clientSecret: 16b70af1ac573e1609bb84a604b4504a18cf7bcd    #生成的clientSecret
  repo: 2633698.github.io    #仓库名称
  owner: 2633698    #github用户名
  admin: 2633698
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-124497414-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0             # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# links
links: [
    {
        title: "个人GitHub",
        href: "https://github.com/2633698	"
    }
]
